### ISSUE TITLE
这个狗日的是骗子，代码一点毛用没用！大家注意！！！

### ISSUE THREAD

**Issue by huawei-hw** [chao325/MaoTai_GUIT#2]
这个狗日的是骗子，代码一点毛用没用！大家注意！！！  花了100买的  P用都没有，大家千万别再上当了，如果有需要可以联系我，我有最新代码。   2972306946@qq.com

**Comment by chao325** [comment]
？？？你傻逼？劳资代码实打实的调用JD后台接口，也有人抢得到。你tm用过？现在开始踩一捧一？ 宣传自己代码，贬低别人？你看过代码么？有能耐就在这唠，代码无用你死全家。

**Comment by chao325** [comment]
看过你的仓库了。是卖300多的对吧。哈哈哈
